version: '2'
services:
  web:
    image: node:10
    build: .
    command: yarn run dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=iic2513template_dev